# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'erpnextApp' do
  erpnextApp_path = '../node_modules/react-native'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{erpnextApp_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: erpnextApp_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{erpnextApp_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{erpnextApp_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{erpnextApp_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{erpnextApp_path}/third-party-podspecs/Folly.podspec"

  # react-native-firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
   
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end